### ISSUE TITLE
OCP NSX 4.15 EMERALD Upgrade Epic

### ISSUE THREAD

**Issue by wmhutchison** [StevenBarre/zh-test-auto#286]
**Describe the epic**
Epic to track all work upgrading EMERALD to OCP 4.15.

**Additional context**
CHG for EMERALD 

**Definition of done**
- [ ] Execute CHG for Registry Prune
- [ ] Execute CHG for OCP upgrade and firmware updates
- [ ] EMERALD upgraded to OCP 4.15
