### ISSUE TITLE
OCP 4.13 SILVER Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [StevenBarre/zh-test-auto#75]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.13.

**Additional context**
CHG for SILVER 

**Definition of done**
- [ ] Execute CHG for Registry Prune
- [ ] Execute CHG for OCP upgrade and firmware updates
- [ ] SILVER upgraded to OCP 4.13
