### ISSUE TITLE
OCP 4.13 GOLD Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [StevenBarre/zh-test-auto#79]
**Describe the epic**
Epic to track all work upgrading GOLD to OCP 4.13.

**CHANGES**
CHG for GOLD

**Definition of done**
- [ ] Execute CHG for OCP upgrade prep
- [ ] Execute CHG for OCP upgrade
- [ ] GOLD upgraded to OCP 4.13
