### ISSUE TITLE
OCP 4.13 GOLDDR Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [StevenBarre/zh-test-auto#83]
**Describe the epic**
Epic to track all work upgrading GOLDDR to OCP 4.13

**CHANGES**
CHG for GOLDDR

**Definition of done**
- [ ] Execute CHG for OCP upgrade prep
- [ ] Execute CHG for OCP upgrade 
- [ ] GOLDDR upgraded to OCP 4.13
